### PR TITLE
fixed bug in VNNIT setup

### PR DESCRIPTION
**Pull request by alheinecke**

### CODE REVIEW

**Comment by alheinecke** [comment]
@rengolin it seems you changed the buildkite config, but the scripts haven't been submitted to repository. Can you please do.

**Comment by rengolin** [comment]
> @rengolin it seems you changed the buildkite config, but the scripts haven't been submitted to repository. Can you please do.

All of the config was added in the main repo, not here. Is there any of those that should be here?

**Comment by alheinecke** [comment]
> All of the config was added in the main repo, not here. Is there any of those that should be here?

Wouldn't it make sense to add the libxsmm-dnn configs to libxsmm-dnn. Also I feel it must be added there, the currently link goes to scripts... and it feel it cannot be in a submodule.

**Comment by rengolin** [comment]
> Wouldn't it make sense to add the libxsmm-dnn configs to libxsmm-dnn. Also I feel it must be added there, the currently link goes to scripts... and it feel it cannot be in a submodule.

Hm, it seems these two don't run in libxsmm, so it should be simpler than  thought

**Review by rengolin — APPROVED** [review]
CI fixed, please rebase

**Pull request merged**
